export enum GenresEnum {
  All = "All",
  Crime = "Crime",
  Documentary = "Documentary",
  Horror = "Horror",
  Comedy = "Comedy",
  Action = "Action",
  Adventure = "Adventure",
  Fantasy = "Fantasy",
  Animation = "Animation",
  Thriller = "Thriller",
  Family = "Family",
  Music = "Music",
  Drama = "Drama",
  War = "War",
  History = "History",
}
